In [9]:
print("Hello")

Hello


In [10]:
import numpy as np

# ----------------   TASK-1 --------------------
print("----------------   TASK-1 --------------------")
# one Dimensional Array
one_dim=np.array([1,2,3,4,5,6,7,8,9,10])
#print(one_dim)

# one Dimensional Array
one_dim_int=np.arange(1,11)
#print(one_dim_int)

# two Dimensional Array
two_dim=np.arange(1,10).reshape(3,3)
#print(two_dim)

# Array with specified 10 steps
array_step=np.arange(10,51,10)
#print(array_step)

print("One Dim Array: " , one_dim_int, ", Shape :",one_dim_int.shape, ", Size:", one_dim_int.size, " and Data Type :",one_dim_int.dtype)
print("Two Dim Array: \n" , two_dim, ", Shape :",two_dim.shape, ", Size:", two_dim.size, " and Data Type :",two_dim.dtype)
print("Array with 10 steps: " , array_step, ", Shape :",array_step.shape, ", Size:", array_step.size, " and Data Type :",array_step.dtype)


# ----------------   TASK-2 --------------------
print("----------------   TASK-2 --------------------")
# Givem two 1D arrays A and B
A=np.array([10,20,30,40])
B=np.array([1,2,3,4])

print("A+B: ",A+B)
print("A-B: ",A-B)
print("A*B: ",A*B)
print("A/B: ",A/B)
print("A**2: ",A**2)

print("-*-"*10)

print("np.add(A,B): ",np.add(A,B))
print("np.subtract(A,B): ",np.subtract(A,B))
print("np.multiply(A,B): ",np.multiply(A,B))
print("np.divide(A,B): ",np.divide(A,B))
print("np.power(A,2): ",np.power(A,2))


# ----------------   TASK-3 --------------------
print("----------------   TASK-3 --------------------")

values=np.array([2,4,6,8,10])
print("Original values: ", values)

print("Square of values: ",np.square(values))
print("Square root of values: ",np.sqrt(values))
print("Exponential of values: ",np.exp(values))
print("Natural Log of values: ",np.log(values))
print("Sum of values: ",np.sum(values))
print("Cumulative sum of values: ",np.cumsum(values,axis=0))


# ----------------   TASK-4 --------------------
print("----------------   TASK-4 --------------------")
data=np.arange(10,91,10).reshape(3,3).astype(int)
print("Original data:",data)

print("Row-wise sum: ",data.sum(axis=1))
print("Column-wise sum: ",data.sum(axis=0))
print("Minimum value: ",data.min())
print("Maximum value: ",data.max())
print("Overall Mean value: ",data.mean())
print("Total sum: ",data.sum())

print("-*-"*10)
print("Using numpy functions")
print("-*-"*10)

print("Row-wise sum: ",np.sum(data, axis=1))
print("Column-wise sum: ",np.sum(data, axis=0))
print("Minimum value: ",np.min(data))
print("Maximum value: ",np.max(data))
print("Overall Mean value: ",np.mean(data))
print("Total sum: ",np.sum(data))

# ----------------   TASK-5 --------------------
print("----------------   TASK-5 --------------------")


marks=np.array([78,85,90,66,72,88,95,60])
print("Oriinal marks: ",marks)

print("Mean of marks: ",np.mean(marks))
print("Median of marks: ", np.median(marks))
print("Varience of marks: ", np.var(marks))
print("Standard Deviation: ", np.std(marks))
print("Max in marks:", np.max(marks))
print("Min in marks:", np.min(marks))
print("Range of marks: ", np.ptp(marks))



# ----------------   TASK-6 --------------------
print("----------------   TASK-6 --------------------")

print("Oriinal marks: ",marks)
print("Sorted marks: ",np.sort(marks))
print("25th percentile: ",np.percentile(marks, 25))
print("50th percentile: ",np.percentile(marks, 50))
print("75th percentile: ",np.percentile(marks, 75))

average_marks = np.mean(marks)
above_average_count = np.sum(marks > average_marks)
print("Average marks: ",average_marks)
print("Number of students who scored above average marks: ",above_average_count)


# ----------------   TASK-7 --------------------
print("----------------   TASK-7 --------------------")
sales=np.array([1200,1500,900,2000,1800,1700,1600])

print("Total sales: ",np.sum(sales))
print("Average daily sales: ",np.mean(sales))
print("Highest sales day: ",np.max(sales))
print("Lowest sales day: ",np.min(sales))
print("Std deviation: ",np.std(sales))

# identify days where sales were above average
average_sales = np.mean(sales)
above_average_days = sales[sales > average_sales]
print("Average sales: ",average_sales)
print("Days with above average sales: ",above_average_days)

# Note: Can copy the whole code and paste in a .py file and run it to see the output.

----------------   TASK-1 --------------------
One Dim Array:  [ 1  2  3  4  5  6  7  8  9 10] , Shape : (10,) , Size: 10  and Data Type : int64
Two Dim Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] , Shape : (3, 3) , Size: 9  and Data Type : int64
Array with 10 steps:  [10 20 30 40 50] , Shape : (5,) , Size: 5  and Data Type : int64
----------------   TASK-2 --------------------
A+B:  [11 22 33 44]
A-B:  [ 9 18 27 36]
A*B:  [ 10  40  90 160]
A/B:  [10. 10. 10. 10.]
A**2:  [ 100  400  900 1600]
-*--*--*--*--*--*--*--*--*--*-
np.add(A,B):  [11 22 33 44]
np.subtract(A,B):  [ 9 18 27 36]
np.multiply(A,B):  [ 10  40  90 160]
np.divide(A,B):  [10. 10. 10. 10.]
np.power(A,2):  [ 100  400  900 1600]
----------------   TASK-3 --------------------
Original values:  [ 2  4  6  8 10]
Square of values:  [  4  16  36  64 100]
Square root of values:  [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential of values:  [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
N